# Jekyll 配置
title: "测试V1"  # 网站标题
description: "欢迎来到我的个人主页，这里记录了我的学习、工作和生活。"  # 网站描述
url: "https://yourdomain.com"  # 你的网站域名
baseurl: ""  # 如果你的网站不在根目录，可以设置子目录路径

# 作者信息
author:
  name: "你的名字"
  email: "your.email@example.com"
  github: "your-github-username"
  twitter: "your-twitter-handle"
  linkedin: "your-linkedin-profile"

# 主题设置
theme: minima  # 你可以选择其他主题，如 "jekyll-theme-cayman"

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 分页设置
paginate: 5  # 每页显示的文章数量
paginate_path: "/blog/page:num"  # 分页路径

# 默认配置
defaults:
  - scope:
      path: ""  # 应用到所有文件
    values:
      layout: "default"  # 默认布局
      author: "你的名字"  # 默认作者

# 导航栏
navigation:
  - name: "首页"
    url: "/"
  - name: "博客"
    url: "/blog/"
  - name: "关于我"
    url: "/about/"
  - name: "项目"
    url: "/projects/"
  - name: "联系"
    url: "/contact/"

# 社交链接
social_links:
  - name: "GitHub"
    url: "https://github.com/your-github-username"
  - name: "Twitter"
    url: "https://twitter.com/your-twitter-handle"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/your-linkedin-profile"

# 其他配置
markdown: kramdown  # 使用的 Markdown 解析器
highlighter: rouge  # 代码高亮工具
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
