# ========== 基础配置 ==========
title: "V3"      # 网站标题
description: "我的技术博客与项目集"  # 网站描述
url: "https://yourusername.github.io"  # GitHub Pages 域名
baseurl: ""                      # 如果项目在仓库子目录（如 `/blog`），此处需填写

# ========== 作者信息（minima 主题专用格式） ========== 
author:
  name: "你的名字"
  email: "your.email@example.com"
  # minima 主题会通过以下字段自动生成社交链接
  github: your-github-username    # 直接填用户名（不要带URL）
  twitter: your-twitter-handle    # 同上
  linkedin: your-linkedin-id      # 同上（填LinkedIn ID，非完整URL）


# ========== GitHub Pages 必需配置 ========== 
theme: minima                     # GitHub Pages 默认支持的主题
plugins:
  - jekyll-feed                   # 允许生成 RSS
remote_theme: pages-themes/minima # 防止本地与 GitHub 环境冲突（二选一）
# 注意：如果用 `remote_theme`，则需要删除本地的 `theme: minima`


# ========== 导航栏（minima 主题默认路径） ========== 
# 默认导航栏路径为：_data/navigation.yml
# (可选) 直接在 _config.yml 中定义：
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      nav_order: 1  # 导航栏顺序


# ========== 其他配置 ========== 
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
